Added functions for deleting locked files.
AutoActuary/deploy-scripts pull request #52
Opened 2020-10-20 12:36 UTC by heetbeet

- Especially helpful for Excel locks.
- Want to use this in the uninstaller when Python is available to the installed program.

2020-10-30 07:30 UTC, rudolfbyker requested changes

2020-10-30 07:30 UTC, rudolfbyker commented on includes/rm_and_kill.py
> +            yield Path(i).absolute()
I think you mean `Path(i).resolve()` ? https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve

2020-10-30 07:30 UTC, rudolfbyker commented on includes/rm_and_kill.py
> +from path import Path as _Path
This package sucks. Change my mind. ;)

2020-10-30 07:30 UTC, rudolfbyker commented on includes/rm_and_kill.py
> +handlebin = this_dir.joinpath("handle64.exe")
We need some documentation of what this exe is and where it comes from.

2020-10-30 07:30 UTC, rudolfbyker commented on includes/rm_and_kill.py
> +    # Put here what would ordinarily go in the `__enter__` method
Don't document how the language works (if you really need to you can link to python docs). Rather document what you are trying to achieve / what the purpose of this function is. Also, use `"""` comments for function docs.

2020-10-30 07:30 UTC, rudolfbyker commented on includes/rm_and_kill.py
> +        print("no not possible")
Do we really want to print this in production code??

2020-10-30 07:30 UTC, rudolfbyker commented on includes/rm_and_kill.py
> +                pass
This will cause an busy loop (high CPU usage) when the file's permissions have changed for some reason. Not good.

2020-11-02 15:16 UTC, heetbeet commented on includes/rm_and_kill.py
> +from path import Path as _Path
- It has the .walk() generator that returns full _Path objects (and not _dir, files, dirs like os.walk())
- It has context manager for changing directories build in.

2020-11-02 15:16 UTC, heetbeet commented on includes/rm_and_kill.py
> +handlebin = this_dir.joinpath("handle64.exe")
Will add:
https://docs.microsoft.com/en-us/sysinternals/downloads/handle

2020-11-02 15:18 UTC, heetbeet commented on includes/rm_and_kill.py
> +        print("no not possible")
Oops, some leftover copy/pasted code

2020-11-02 15:20 UTC, heetbeet commented on includes/rm_and_kill.py
> +                pass
Okay, I only use this in tests, but that is no excuse for a sloopy function. Do you think I should add a time.sleep or what is the best way to overcome a busy loop?

2020-11-02 15:24 UTC, heetbeet commented on includes/rm_and_kill.py
> +            yield Path(i).absolute()
Hmm, `.absolute()` works just fine. Wonder why it isn't documented. Will change to `.resolve()` though.

2020-11-02 15:31 UTC, rudolfbyker commented on includes/rm_and_kill.py
> +from path import Path as _Path
I will investigate again. Anyway, it's lacking a few things that I use often in the standard pathlib, which kind of sucks. But if we need it for context manager and walk, that makes sense.

2020-11-02 15:36 UTC, rudolfbyker commented on includes/rm_and_kill.py
> +                pass
If it's only used in tests, but it in a separate file and write in the doc string "this is only used in tests".

Never mind busy loop, why do you need a loop at all? Just let the test fail if you fail to remove the file. Or if you really need to wait for the process to end, use p.kill() followed by p.join() or something like that. Worst case, if you really need to loop, add time.sleep() and a maximum number of retries before throwing an error.

2020-11-02 15:39 UTC, heetbeet commented on includes/rm_and_kill.py
> +            yield Path(i).absolute()
Hmm, if I change all my `.absolute()` to `.resolve()1 some of my tests starts failing. It seems like Python doesn't like to `.resolve()` a filepath if some permissions are set on the file. I will change `.resolve()` over here, and at a few other places though.

2020-11-02 15:51 UTC, heetbeet commented on includes/rm_and_kill.py
> +            yield Path(i).absolute()
Oh and wait, I don't want to `resolve` symlinks when walking.
There is a whole discussion on this:
https://discuss.python.org/t/pathlib-absolute-vs-resolve/2573/

This answer sums it up nicely:
https://discuss.python.org/t/pathlib-absolute-vs-resolve/2573/5

Damn, this is annoying. Maybe I should just add my own abspath.

2020-11-02 15:55 UTC, heetbeet commented on includes/rm_and_kill.py
> +            yield Path(i).absolute()
-1 for pathlib!

2020-11-02 15:58 UTC, heetbeet commented on includes/rm_and_kill.py
> +            yield Path(i).absolute()
I fixed it by switching to `Path(os.path.abspath(path))` wherever I'm unsure if `.resolve()` might give some crazy error.

2020-11-02 16:04 UTC, heetbeet commented on includes/rm_and_kill.py
> +                pass
Okay, I added that this is used for testing.

2020-11-02 16:06 UTC, merged